# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: fe project CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run build
        # 命名这个任务为发布Deploy
        # - name: Deploy
        #   # 因为构建之后，需要把代码上传到服务器上，所以需要连接到ssh，并且做一个拷贝操作
        #   uses: cross-the-world/scp-pipeline@master
        #   env:
        #     WELCOME: 'ssh scp ssh pipelines'
        #     LASTSSH: 'Doing something after copying'
        #   with:
        #     host: ${{ secrets.USER_HOST }}
        #     user: ${{ secrets.USER_NAME }}
        #     pass: ${{ secrets.USER_PASS }}
        #     connect_timeout: 10s
        #     local: './dist/*'
        #     remote: /home/www/dist
